### ISSUE TITLE
I am talking about the ng2-file-manager . I am facing issue for this project.

### ISSUE THREAD

**Issue by VIPINSAINI17** [jkuri/ng2-file-manager#1]

**Comment by VIPINSAINI17** [comment]
Prepairing project for production, please wait...
-------------------------------------------------------
C:\Users\VIPINK\src\ng2-file-manager\dist deleted.
/public dir successfully copied to dist.
index.html generated at C:\Users\VIPINK\src\ng2-file-manager\dist\index.html
SASS compiled in 67ms
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn rollup ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "roll"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! angular2-rollup-starter@1.0.0 roll: `node ./scripts/cmd.js dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-rollup-starter@1.0.0 roll script 'node ./scripts/cmd.js dist'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-rollup-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/cmd.js dist
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-rollup-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-rollup-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\VIPINK\src\ng2-file-manager\npm-debug.log

**Comment by jkuri** [comment]
Clone the latest now, I updated it for you.

**Comment by VIPINSAINI17** [comment]
I appreciate your prompt help .. thanks :)
